### ISSUE TITLE
Several problems with TH

### ISSUE THREAD

**Issue by xgrommx** [sjoerdvisscher/free-functors#3]
Hello @sjoerdvisscher 
I have some problem with version 0.8.1
https://gist.github.com/xgrommx/2f7a947258e7d3b9cda6c1aaeeaf17a9
Also I have problem with version 0.8
https://gist.github.com/xgrommx/29c2276f9f1c3c27b2e6adaf3a2b9efa

**Comment by sjoerdvisscher** [comment]
Fixed in 0.8.2!

https://github.com/sjoerdvisscher/free-functors/blob/master/examples/Sem.hs
