### ISSUE TITLE
Instance of MonadTrans, MFunctor etc for HFree

### ISSUE THREAD

**Issue by xgrommx** [sjoerdvisscher/free-functors#6]
Hello @sjoerdvisscher. How about add an instance of `MonadTrans`, `MFunctor` for `HFree`?

For example:
`MonadTrans`, `lift` will be like `liftFree`
`MFunctor`, `hoist` will be like `hfmap`

**Comment by sjoerdvisscher** [comment]
See https://github.com/sjoerdvisscher/free-functors/blob/master/src/Data/Functor/HFree.hs#L98

**Comment by xgrommx** [comment]
@sjoerdvisscher interesting, I do it now like

```haskell
newtype Freer f a = Freer { runFreer :: HFree Monad f a }
  deriving (Functor, Applicative, Monad) via HFree Monad f

type Eff r = Freer (Union r)

instance MonadTrans Freer where
  lift = liftEff

instance MFunctor Freer where
  hoist = hoistEff

hoistEff :: (f ~> g) -> Freer f ~> Freer g
hoistEff f = Freer . hfmap f . runFreer

liftEff :: f ~> Freer f
liftEff = Freer . liftFree
```

**Comment by sjoerdvisscher** [comment]
If you use this code and it works for you, I think I should add the instances and just document the issue. I don't think there can be any other instance so providing them would do no harm.

**Comment by xgrommx** [comment]
@sjoerdvisscher another question. Could u show some example with `Free` + `Algebra`, where `Algebra` is

```
class Algebra f where
  alg :: f a -> a
```

**Comment by xgrommx** [comment]
@sjoerdvisscher I found your answer https://stackoverflow.com/questions/14852712/is-there-a-generalization-of-these-free-like-constructions/15086576#15086576

But what should be instead of question mark?

```
class Algebra f t where
  alg :: f t -> t

type FreeAlgebra f a = Free (Algebra f) a


freeAlg = ?
```

**Comment by sjoerdvisscher** [comment]
@xgrommx I think that should be

```haskell
freeAlg :: f (FreeAlgebra f a) -> FreeAlgebra f a
freeAlg fa = Free $ \k -> alg (fmap (rightAdjunct k) fa))
```
